version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::891377081281:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-ETvHv0IpMKvS"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::891377081281:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-Ft6MN7fXxzLo"
cloudformation_execution_role = "arn:aws:iam::891377081281:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-4A2EvCHK1E6H"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-70gw2jtzeamn"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::891377081281:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-KsEokTnPFBHl"
cloudformation_execution_role = "arn:aws:iam::891377081281:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-2izcPGz4sRxx"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-624r9utmunjy"
image_repository = ""
region = "us-east-1"
