version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - echo 'Running unit tests'
      - pip3 install pytest pytest-mock
      - python3 -m pytest tests/unit
